<?php
require_once($_SERVER['DOCUMENT_ROOT']."/qr/includes/config.php");
require_once(LIB_PATH."log.php");
require_once(LIB_PATH."logReadable.php");
require_once(LIB_PATH."database.php");
require_once(LIB_PATH."databaseObject.php");
require_once(LIB_PATH."user.php");
require_once(LIB_PATH."admin.php");
require_once(LIB_PATH."session.php");
